name: Terraform Dev Destroy

on:
  workflow_dispatch:

env:
  AWS_REGION: 'us-east-2'
  WORKSPACE: 'dev'
  TF_VARS_FILE: 'dev.tfvars'

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Workspace
        run: terraform workspace select -or-create=true ${{ env.WORKSPACE }}

      - name: Terraform Destroy
        run: terraform apply -destroy -input=false -auto-approve -var-file=${{ env.TF_VARS_FILE}}
